### ISSUE TITLE
Button position is not absolute in certain urls (have to scroll to bottom of page to see it)

### ISSUE THREAD

**Issue by frizensami** [UseCrowdWise/crowdwise#58]
https://blog.saeloun.com/2022/02/23/rails-fiber-safe-connection-pools.html 

![image](https://user-images.githubusercontent.com/5507069/155558711-38b8776c-99c0-4ec2-a509-8d8309c2c340.png)

^ before scrolling all the way down

![image](https://user-images.githubusercontent.com/5507069/155558690-70b8dc55-080e-46ab-8240-0eba0d211305.png)

^ After all the way down

**Comment by yewsiang** [comment]
Problem happens because of a well known problem where transforms applied on the parent will cause "position: fixed" to be buggy. The solution seems to be quite hacky and involved, probably worth investigating in the future:

Relevant discussions:
- https://stackoverflow.com/questions/21091958/css-fixed-child-element-positions-relative-to-parent-element-not-to-the-viewpo
- https://stackoverflow.com/questions/52937708/why-does-applying-a-css-filter-on-the-parent-break-the-child-positioning
- https://stackoverflow.com/questions/2637058/positions-fixed-doesnt-work-when-using-webkit-transform

Disabling transforms on the parent (body tag) fixes the problem:
![Screenshot 2022-02-27 at 11 00 55 AM](https://user-images.githubusercontent.com/14248879/155866557-97da8c18-a0c9-452e-9630-d3b557a20ebd.png)

**Comment by frizensami** [comment]
Wow, that's pretty nuts haha. Noted for future release.

**Comment by yewsiang** [comment]
No fix for now because not common and too much effort
